# Generated by Django 4.2 on 2023-06-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oname', models.CharField(max_length=20, null=True)),
                ('department', models.CharField(max_length=20)),
                ('event', models.CharField(max_length=40)),
                ('date', models.DateField(max_length=20)),
                ('starttime', models.TimeField(null=True)),
                ('endtime', models.TimeField(null=True)),
            ],
        ),
    ]
